/**
 * Created by Nicolo on 2016-03-28.
 */

var DEFAULT_HEATING_BASE_TEMP = 'DEFAULT_HEATING_BASE_TEMPERATURE';
var DEFAULT_COOLING_BASE_TEMP = 'DEFAULT_COOLING_BASE_TEMPERATURE';
var DEFAULT_TEMP_UNIT = 'DEFAULT_TEMPERATURE_NORMALIZE_UNIT';

var WEATHER_NORMALIZE_SYS_CONFIG_KEYS = [DEFAULT_COOLING_BASE_TEMP, DEFAULT_HEATING_BASE_TEMP, DEFAULT_TEMP_UNIT];

var ROLE_DELIMETER = '::';
